#!/bin/bash
# To start n_seeds trials:
#   ./run $(seq 1 n_seeds) 
# To run trial 1 and 3:
#  ./run 1 3
set -e

# confirm all arguments are numbers
for i in $@; do
    if ! [[ $i =~ ^[0-9]+$ ]]; then
        echo "Error: $i is not a number"
        exit 1
    fi
done

function create_seeds {
    dir=$1
    # seeds is a list of numbers, the remaining arguments
    for i in ${@:2}; do
        seed=$RANDOM
        # create seed dir if it doesn't exist
        if [ ! -d "$dir/$i" ]; then
            mkdir $dir/$i
        fi
        # copy config.jl to seed dir but replace {SEED} with $seed
        sed "s/{SEED}/$seed/g" $dir/config.jl > $dir/$i/config.jl
    done
}

function run_seeds {
    dir=$1
    # iterate over all children directories
    # and run config.jl in each
    for i in ${@:2}; do
        if [ -d "$dir/$i" ] && [ -f "$dir/$i/config.jl" ]; then
            runlog="$dir/$i/run.log"
            git rev-parse HEAD > $runlog
            julia -t 4 $dir/$i/config.jl >> $runlog &
        fi
    done
}

if [ $# -eq 0 ]; then
    echo "Usage: run <nseeds>"
    exit 1
fi

# find directories or symlinks
xdirs=$(find . -mindepth 2 -maxdepth 2 -type d -o -type l | sort -r | fzf --multi)

# Compute start time
start=$(date +%s)

echo "Start time: $(date)"

IFS=$'\n'
for xdir in $xdirs; do
    echo "Running $xdir"
    create_seeds $xdir $@
    run_seeds $xdir $@

done
unset IFS

wait

end=$(date +%s)
echo "End time: $(date)"
runtime=$((end-start))
echo "Total runtime: $runtime seconds"
