#!/bin/bash
set -e

function create_seeds {
    nseeds=$1
    dir=$2
    for i in $(seq 1 $nseeds); do
        seed=$RANDOM
        # create seed dir if it doesn't exist
        if [ ! -d "$dir/$i" ]; then
            mkdir $dir/$i
        fi
        # copy config.jl to seed dir but replace {SEED} with $seed
        sed "s/{SEED}/$seed/g" $dir/config.jl > $dir/$i/config.jl
    done
}

function run_seeds {
    dir=$1
    # iterate over all children directories
    # and run config.jl in each
    for i in $(ls $dir); do
        if [ -d "$dir/$i" ]; then
            git rev-parse HEAD > $xdir/run.log
            julia $dir/$i/config.jl >> $dir/$i/run.log &
        fi
    done
}

if [ $# -eq 0 ]; then
    echo "Usage: run <nseeds>"
    exit 1
fi

nseeds=$1
# find directories or symlinks
xdirs=$(find . -mindepth 2 -maxdepth 2 -type d -o -type l | fzf --multi)

IFS=$'\n'
for xdir in $xdirs; do
    echo "Running $xdir"
    create_seeds $nseeds $xdir
    run_seeds $xdir
done
unset IFS

wait
